- name: install VMWare Harbor registry
  hosts: all
  roles:
    - mkgin.vmware-harbor
  vars:
    - harbor_hostname: 35.226.42.2
    - harbor_install_skip_docker_compose: True
    - harbor_install_upload_localcopy_of_installer: /tmp/harbor-offline-installer-v1.1.2.tgz
